### PR TITLE
[Matrix] migrate matrix singleton to multiple matrices 

### PR DESCRIPTION
**Pull request by Herklos**
Should also resolve https://github.com/Drakkar-Software/OctoBot-Evaluators/issues/17

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
I suggest we wait for https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/25 to release 1.4

**Comment by Herklos** [comment]
> I suggest we wait for #25 to release the 1.4 tag

Why ?

**Comment by GuillaumeDSM** [comment]
> > I suggest we wait for #25 to release the 1.4 tag
> 
> Why ? There is no relation between them.

To include everything in one version in case they get merged approx at the same time

**Comment by Herklos** [comment]
> > > I suggest we wait for #25 to release the 1.4 tag
> > 
> > 
> > Why ? There is no relation between them.
> 
> To include everything in one version in case they get merged approx at the same time

I don't really like this way, I prefer to have 2 version approx at the same time but with 2 different changelog to identify them.

**Pull request merged**
